export const SIGNIN_REQUEST ="SIGNIN_REQUEST"
export const SIGNIN_SUCCESS ="SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "SIGNIN_FAIL"
export const SIGNINOUT= 'SIGNINOUT'

export const REGISTER_REQUEST ="REGISTER_REQUEST"
export const REGISTER_SUCCESS ="REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
